routes/web.php
<?php

use App\Http\Controllers\MailingController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\TrainingSessionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::resource('roles', RoleController::class);
Route::resource('mailings', MailingController::class);

Route::resource('surveys', SurveyController::class)->only('create', 'store');
Route::get('surveys/thanks', [SurveyController::class, 'thanks'])->name('surveys.thanks');
Route::resource('sessions', TrainingSessionController::class);
Route::get('/topics/all', [TopicController::class, 'all'])->name('topics.all');

Route::get('anvayasurvey', [SurveyController::class, 'create'])->name('guest-survey');

Route::middleware(['auth:sanctum', 'verified'])->group(function(){

    Route::resource('users', UserController::class);
    Route::resource('surveys', SurveyController::class)->only('index');
    Route::resource('topics', TopicController::class);
    Route::get('/send-newsletter', [NewsletterController::class, 'index'])->name('newsletter.index');
    Route::post('/send-newsletter', [NewsletterController::class, 'send'])->name('newsletter.send');
    Route::get('/send-newsletter/progress', [NewsletterController::class, 'progress'])->name('newsletter.progress');
    Route::get('/', function(){
        return view('home');
    })->name('home');
});

Route::get('/dashboard', function(){
    return view('dashboard');
})->name('dashboard');

app/Models/Topic.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Topic extends Model
{
    use HasFactory;

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function topics(): HasMany
    {
        return $this->hasMany(TrainingSession::class, 'topic_id');
    }

    protected $fillable = [
        'name', 'detail',
    ];

    protected $casts = [
        'training_date' => 'date:M d, y',
        'training_time' => 'datetime:H:i',
    ];
}

app/Http/Controllers/API/TopicController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Topic;
use Illuminate\Http\Request;

class TopicController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topic = Topic::orderBy('created_at', 'DESC')->get();

        return $topic;
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/TopicController.php
<?php
    
namespace App\Http\Controllers;

use App\Http\Requests\TopicRequest;
use App\Models\Topic;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TopicController extends Controller
{ 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:topic-list|topic-create|topic-edit|topic-delete', ['only' => ['index','show']]);
         $this->middleware('permission:topic-create', ['only' => ['create','store']]);
         $this->middleware('permission:topic-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:topic-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::where('user_id', Auth::user()->id)->orderBy('created_at', 'DESC')->paginate(5);
        $pageTitle = 'My Topic';
        return view('topics.all', compact('topics', 'pageTitle'));
    }
    
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function all()
    {
        $topics = Topic::orderBy('created_at', 'DESC')->paginate(5);
        $pageTitle = 'All Topic';
        return view('topics.all', compact('topics', 'pageTitle'));
    }
    

    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('topics.create');
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TopicRequest $request)
    {
        $topic = new Topic;
        $topic->user_id = Auth::user()->id;
        $topic->topic_name = $request->get('topic_name');
        $topic->topic_detail = $request->get('topic_detail');
        $topic->training_method = $request->get('training_method');
        $topic->training_date = $request->get('training_date');
        $topic->training_time = $request->get('training_time');
        $topic->training_location = $request->get('training_location');
        $topic->training_duration = $request->get('training_duration');
        $topic->status = $request->get('status');
        $topic->save();
    
        return redirect()->route('topics.index')
                        ->with('success','Topic created successfully.');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function show(Topic  $topic)
    {
        return view('topics.show',compact('topic'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function edit(Topic  $topic)
    {
        return view('topics.edit', compact('topic'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function update(TopicRequest $request, Topic $topic)
    {    
        $topic->topic_name = $request->get('topic_name');
        $topic->topic_detail = $request->get('topic_detail');
        $topic->training_method = $request->get('training_method');
        $topic->training_date = $request->get('training_date');
        $topic->training_time = $request->get('training_time');
        $topic->training_location = $request->get('training_location');
        $topic->status = $request->get('status');
        $topic->save();
    
        return redirect()->route('topics.index')
                        ->with('success','Topic updated successfully');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Topic  $topic
     * @return \Illuminate\Http\Response
     */
    public function destroy(Topic  $topic)
    {
        try {
            $topic->delete();
        } catch (\Throwable $th) {
            abort(500);
        }
    
        return redirect()->route('topics.index')
                        ->with('success','Topic deleted successfully');
    }

    public function fetch(Request $request)
    {
        $trainerId = $request->get('trainer_id');

        $topics = Topic::where('user_id', $trainerId)->where('status', 'open')->get();

        return $topics;
    }

    public function fetchInfo(Topic $topic)
    {
        return $topic;
    }
}

resources/views/topics/all.blade.php
@extends('layouts.apps')


@section('content')

@if ($message = Session::get('success'))
<div class="alert alert-success">
    <p>{{ $message }}</p>
</div>
@endif

<div class="flex flex-col">
    <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
            <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="w-full table-fixed divide-y divide-gray-200">
                    <thead class="bg-gray-800">
                        <tr>
                            <th scope="col" class="px-6 w-5 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                No
                            </th>
                            <th scope="col" class="px-6 w-1/9 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                Topic
                            </th>
                            <th scope="col" class="px-6 w-1/9 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                Trainer
                            </th>
                            <th scope="col" class="px-6 w-1/9 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                Method <br> Location
                            </th>
                            <th scope="col" class="px-6 w-1/9 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                Date <br> Time
                            </th>
                            <th scope="col" class="px-6 w-1/9 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                Duration
                            </th>
                            <th scope="col" class="px-6 w-1/9 py-3 text-left text-xs font-medium text-white uppercase tracking-wider">
                                Status
                            </th>
                            <th scope="col" class="relative px-6 w-1/9 py-3">
                                <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        @foreach ($topics as $topic )
                        <tr>
                            
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {{ $loop->index + 1 }}
                            </td>
                            <td class="px-6 py-4">
                                <div class="text-sm text-gray-900 uppercase">{{ $topic->topic_name }}</div>
                                <div class="text-sm text-gray-500 truncate w-48">{{ $topic->topic_detail }}</div>
                            </td>
                            
                            <td class="w-1/8 px-6 py-4 whitespace-nowrap">
                                <div class=" ">
                                    <div class="text-sm font-medium text-gray-900">{{ $topic->user->name }}</div>
                                    <div class="text-sm text-gray-500">{{ $topic->user->email }}</div>
                                </div>
                            </td>
                            <td class="w-1/8 px-6 py-4 whitespace-nowrap">
                                <div class=" ">
                                    <div class="text-sm font-medium text-gray-900">{{ $topic->training_method }}</div>
                                    <div class="text-sm text-gray-500 truncate w-40">{{ $topic->training_location }}</div>
                                </div>
                            </td>
                            <td class="w-1/8 px-6 py-4 whitespace-nowrap">
                                <div class=" ">
                                    <div class="text-sm font-medium text-gray-900">{{ $topic->training_date->format('M d, y') }}</div>
                                    <div class="text-sm text-gray-500">{{ $topic->training_time->format('H:i') }}</div>
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {{ $topic->training_duration }} minutes
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="{{ $topic->status =='close' ? 'bg-red-100 text-red-800': 'bg-green-100 text-green-800' }} px-2 inline-flex text-xs leading-5 font-semibold rounded-full">
                                    {{ $topic->status }}
                                </span>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                <form action="{{ route('topics.destroy', $topic->id) }}" method="post" class="flex">
                                    <a href="{{ route('topics.edit', $topic->id) }}" class="" alt='edit'>
                                        <i>
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="#60A5FA">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                                            </svg>
                                        </i>
                                    </a>
                                    
                                    @csrf
                                    @method('DELETE')
                                    
                                    <button type="submit" class="">
                                        <i>
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="#DB2777">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                                            </svg>
                                        </i>
                                    </button>
                                    
                                </form>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
            {!! $topics->links() !!}
        </div>
    </div>
</div>



@endsection

resources/views/topics/create.blade.php
@extends('layouts.apps')

@section('content')

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('topics.store') }}" method="POST">
    @csrf
    @method('POST')
    
    <div class="mt-10 sm:mt-0">
        <div class="md:grid md:grid-cols-3 md:gap-6">
            <div class="md:col-span-1">
                <div class="px-4 sm:px-0">
                    <h3 class="text-lg font-medium leading-6 text-gray-900">Information</h3>
                    <p class="mt-1 text-sm text-gray-600">
                        Training topic should be created only by related trainer because it will colerate to trainer's KPI. <br> <br>
                        <strong>Training Status</strong> defines availability of the related topics. <strong>Topic Close</strong> means trainee will not be abel to fill the absence of given topic.
                    </p>
                </div>
            </div>
            <div class="mt-5 md:mt-0 md:col-span-2">
                <form action="#" method="POST">
                    <div class="shadow overflow-hidden sm:rounded-md">
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <div class="grid grid-cols-6 gap-6">
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="topic_name" class="block text-sm font-medium text-gray-700">Topic Title</label>
                                    <input type="text" name="topic_name" id="topic_name" autocomplete="topic_name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Training Topic">
                                </div>
                                
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="training_method" class="block text-sm font-medium text-gray-700">Method</label>
                                    <select type="text" name="training_method" id="training_method" autocomplete="training_method" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                        <option value="class">Class</option>
                                        <option value="briefing">Briefing</option>
                                        <option value="role-play">Role-Play</option>
                                        <option value="online-essay">Online-Essay</option>
                                        <option value="online-webinar">Online-Webinar</option>
                                        <option value="one-on-one">One-on-One</option>
                                    </select>
                                </div>
                                <div class="col-span-6">
                                    <label for="topic_detail" class="block text-sm font-medium text-gray-700">Topic Detail</label>
                                    <textarea type="text" name="topic_detail" id="topic_detail" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Further detail related to the topic"></textarea>
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="training_date" class="block text-sm font-medium text-gray-700">Training Date</label>
                                    <input type="date" name="training_date" id="training_date" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="training_time" class="block text-sm font-medium text-gray-700">Training Time</label>
                                    <input type="time" name="training_time" id="training_time" autocomplete="training_time" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="training_duration" class="block text-sm font-medium text-gray-700">Duration (minutes)</label>
                                    <input type="number" name="training_duration" id="training_duration" autocomplete="training_duration" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Minimal 15 minutes">
                                </div>
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="training_location" class="block text-sm font-medium text-gray-700">Location</label>
                                    <input type="text" name="training_location" id="training_location" autocomplete="training_location" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Location or training link if the session is online">
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="status" class="block text-sm font-medium text-gray-700">Status</label>
                                    <select type="text" name="status" id="status" autocomplete="status" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Minimal 15 minutes">
                                        <option value="open">Open</option>
                                        <option value="close">Close</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</form>


@endsection

resources/views/topics/edit.blade.php
@extends('layouts.apps')

@section('content')

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('topics.update', $topic->id) }}" method="POST">
    @csrf
    @method('PATCH')
    
    <div class="mt-10 sm:mt-0">
        <div class="md:grid md:grid-cols-3 md:gap-6">
            <div class="md:col-span-1">
                <div class="px-4 sm:px-0">
                    <h3 class="text-lg font-medium leading-6 text-gray-900">Information</h3>
                    <p class="mt-1 text-sm text-gray-600">
                        Training topic should be created only by related trainer because it will colerate to trainer's KPI. <br> <br>
                        <strong>Training Status</strong> defines availability of the related topics. <strong>Topic Close</strong> means trainee will not be abel to fill the absence of given topic.
                    </p>
                </div>
            </div>
            <div class="mt-5 md:mt-0 md:col-span-2">
                
                <div class="shadow overflow-hidden sm:rounded-md">
                    <div class="px-4 py-5 bg-white sm:p-6">
                        <div class="grid grid-cols-6 gap-6">
                            <div class="col-span-6 sm:col-span-3">
                                <label for="topic_name" class="block text-sm font-medium text-gray-700">Topic Title</label>
                                <input type="text" name="topic_name" value="{{ $topic->topic_name }}" id="topic_name" autocomplete="topic_name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Training Topic">
                            </div>                          
                            <div class="col-span-6 sm:col-span-3">
                                <label for="training_method" class="block text-sm font-medium text-gray-700">Method</label>
                                <select type="text" name="training_method" value="{{ $topic->training_method }}" id="training_method" autocomplete="training_method" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    <option value="class">Class</option>
                                    <option value="briefing">Briefing</option>
                                    <option value="role-play">Role-Play</option>
                                    <option value="online-essay">Online-Essay</option>
                                    <option value="online-webinar">Online-Webinar</option>
                                    <option value="one-on-one">One-on-One</option>
                                </select>
                            </div>
                            <div class="col-span-6">
                                <label for="topic_detail" class="block text-sm font-medium text-gray-700">Topic Detail</label>
                                <input type="text" name="topic_detail" value="{{ $topic->topic_detail }}" id="topic_detail" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            </div>
                            <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                <label for="training_date" class="block text-sm font-medium text-gray-700">Training Date</label>
                                <input type="date" name="training_date" value="{{ $topic->training_date->format('Y-m-d') }}" id="training_date" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            </div>
                            <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                <label for="training_time" class="block text-sm font-medium text-gray-700">Training Time</label>
                                <input type="time" name="training_time" value="{{ $topic->training_time->format('H:i:s') }}" id="training_time" autocomplete="training_time" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            </div>
                            <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                <label for="training_duration" class="block text-sm font-medium text-gray-700">Duration (minutes)</label>
                                <input type="number" name="training_duration" value="{{ $topic->training_duration }}" id="training_duration" autocomplete="training_duration" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            </div>
                            <div class="col-span-6 sm:col-span-3">
                                <label for="training_location" class="block text-sm font-medium text-gray-700">Location</label>
                                <input type="text" name="training_location" value="{{ $topic->training_location }}" id="training_location" autocomplete="training_location" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                            </div>
                            <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                <label for="status" class="block text-sm font-medium text-gray-700">Status</label>
                                <select type="text" name="status" value="{{ $topic->status }}" id="status" autocomplete="status" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    <option value="open">Open</option>
                                    <option value="close">Close</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                        <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                            Save
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</form>


@endsection

resources/views/topics/show.blade.php
@extends('layouts.apps')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Topic</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('topics.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $topic->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $topic->detail }}
            </div>
        </div>
    </div>
@endsection