routes/web.php
<?php

use App\Http\Controllers\MailingController;
use App\Http\Controllers\NewsletterController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SurveyController;
use App\Http\Controllers\TopicController;
use App\Http\Controllers\TrainingSessionController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('home');
// });

Route::resource('roles', RoleController::class);
Route::resource('mailings', MailingController::class);

Route::resource('surveys', SurveyController::class)->only('create', 'store');
Route::get('surveys/thanks', [SurveyController::class, 'thanks'])->name('surveys.thanks');
Route::resource('sessions', TrainingSessionController::class);
Route::get('/topics/all', [TopicController::class, 'all'])->name('topics.all');

Route::get('anvayasurvey', [SurveyController::class, 'create'])->name('guest-survey');

Route::middleware(['auth:sanctum', 'verified'])->group(function(){

    Route::resource('users', UserController::class);
    Route::resource('surveys', SurveyController::class)->only('index');
    Route::resource('topics', TopicController::class);
    Route::get('/send-newsletter', [NewsletterController::class, 'index'])->name('newsletter.index');
    Route::post('/send-newsletter', [NewsletterController::class, 'send'])->name('newsletter.send');
    Route::get('/send-newsletter/progress', [NewsletterController::class, 'progress'])->name('newsletter.progress');
    Route::get('/', function(){
        return view('home');
    })->name('home');
});

Route::get('/dashboard', function(){
    return view('dashboard');
})->name('dashboard');

app/Models/Survey.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Survey extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
        'title',
        'guest_email',
        'departure_date',
        'arrival_date',
        'arrival_time',
        'carier_code',
        'eta',
        'preference_bed',
        'preference_food',
        'transfer',
        'special_request',
        
    ];

    protected $cast = [
        'departure_date' => 'date:M d, y',
        'arrival_date' => 'date:M d, y',
    ];

    protected $dates = [
        'departure_date',
        'arrival_date'
    ];

}

app/Http/Controllers/SurveyController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SurveyResponse;
use App\Models\Mailing;
use App\Models\Survey;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\Mail;

class SurveyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $surveys = Survey::orderBy('created_at', 'DESC')->paginate(10);

        return view('surveys.index', compact('surveys'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $hash = $request->get('u', '');
        $id = Crypt::decrypt($hash);
        $mailing = Mailing::find($id);
        return view('surveys.create', compact('mailing'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $survey = new Survey;
        $survey->name = $request->get('name');
        $survey->title = $request->get('title');
        $survey->arrival_date = $request->get('arrival_date');
        $survey->departure_date = $request->get('departure_date');
        $survey->arrival_time = $request->get('arrival_time');
        $survey->carier_code = $request->get('carier_code');
        $survey->eta = $request->get('eta');
        $survey->preference_bed = $request->get('preference_bed');
        $survey->preference_food = $request->get('preference_food');
        $survey->transfer = $request->get('transfer');
        $survey->guest_email = $request->get('guest_email');
        $survey->special_request = $request->get('special_request');
        $survey->save();

        Mail::to(config('email.reception'))->send(new SurveyResponse($survey));

        return redirect()->route('surveys.thanks');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function show(Survey $survey)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function edit(Survey $survey)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Survey $survey)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function destroy(Survey $survey)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Survey  $survey
     * @return \Illuminate\Http\Response
     */
    public function thanks()
    {
        return view('surveys.thanks');
    }
}

resources/views/surveys/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{{ mix('css/app.css') }}">
  <title>The ANVAYA Beach Resort Bali - Arrival survey</title>
</head>
<body class="bg-gray-100 flex bg-local" style="background: url('./assets/svg/architect.svg')">
  <div class="bg-gray-100 mx-auto max-w-6xl py-20 px-12 lg:px-24 shadow-xl mb-24">
    <div class="flex item-center justify-center">
      <img src="https://theanvayabali.com/frontend/images/material/logo.png" alt="logo">
      <br>
    </div>
    <div class="p-6">
      <p class="w-full">Dear {{ $mailing->guest_name }},</p>
      <p class="w-full">To make your stay the most memorable one, kindly fill this pre-arrival form</p>
    </div>

    {{-- erorr message --}}
    @if ($errors->any())
    <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
      <strong>Whoops!</strong> There were some problems with your input.<br><br>
      <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
      </ul>
      <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
        <svg class="fill-current h-6 w-6 text-blue-500" role="button" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Close</title><path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/></svg>
      </span>
    </div>
    @endif


    {{-- input form --}}
    <form action="{{ route("surveys.store") }}" method="POST">
      @csrf
      @method('POST')

      <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 flex flex-col">
        <div class="-mx-3 md:flex mb-6">
          <div class="md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="name">
              Name
            </label>
            <input name="name" value="{{ $mailing->guest_name }}" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="name" type="text" placeholder="Name">
          </div>
          <div class="md:w-1/2 px-3">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="title">
              Title
            </label>
            <select name="title" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="title" type="text" placeholder="">
              <option value="">--please select--</option>
              <option value="Mr.">Mr.</option>
              <option value="Mrs.">Mrs.</option>
              <option value="Ms.">Ms.</option>
            </select>
            
          </div>
        </div>
        <div class="-mx-3 md:flex mb-6">
          <div class="md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="guest_email">
              Email
            </label>
            <input name="guest_email" value="{{ $mailing->guest_email }}" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="guest_email" type="text" placeholder="name@mail.com">
          </div>
        </div>
        <div class="-mx-3 md:flex mb-2">
          <div class="md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="arrival_date">
              Arrival Date
            </label>
            <div>
              <input name="arrival_date" value="{{ $mailing->arrival }}" type="date" class="w-full bg-gray-200 border border-gray-200 text-black text-xs py-3 px-4 pr-8 mb-3 rounded" id="departure_date">
            </div>
          </div>
          <div class="md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="departure_date">
              Departure Date
            </label>
            <div>
              <input name="departure_date" type="date" class="w-full bg-gray-200 border border-gray-200 text-black text-xs py-3 px-4 pr-8 mb-3 rounded" id="departure_date">
            </div>
          </div>
          <div class="md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="carier_code">
              Carier Code
            </label>
            <div>
              <input name="carier_code" type="text" class="w-full bg-gray-200 border border-gray-200 text-black text-xs py-3 px-4 pr-8 mb-3 rounded" id="carier_code" placeholder="your flight detail">
            </div>
          </div>
          <div class="md:w-1/2 px-3 mb-6 md:mb-0">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="eta">
              ETA
            </label>
            <div>
              <input name="eta" type="text" class="w-full bg-gray-200 border border-gray-200 text-black text-xs py-3 px-4 pr-8 mb-3 rounded" id="carier_code" placeholder="flight time">
            </div>
          </div>
        </div>
        <div class="-mx-3 md:flex mb-6">
          <div class="md:w-full px-3">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="transfer">
              Airport Transfer
            </label>
            <select name="transfer" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="transfer" type="text">
              <option value="">--please select--</option>
              <option value="Innova 150K">Innova (up to 3 person) at IDR 150,000/car/way</option>
              <option value="Innova 150K">Hi-Ace (up to 10 person) at IDR 500,000/car/way</option>
            </select>
          </div>
          <div class="md:w-full px-3">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="preference_bed">
              Bedding Preferences
            </label>
            <select name="preference_bed" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="preference_bed" type="text">
              <option value="">--please select--</option>
              <option value="King">King Bed (1 Large Bed)</option>
              <option value="Twin">Twin Bed (2 separate Beds)</option>
            </select>
          </div>
        </div>
        <div class="-mx-3 md:flex mb-6">
          <div class="md:w-full px-3">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="preference_food">
              Food Preferences
            </label>
            <input name="preference_food" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="preference_food" type="text" placeholder="dietary, allergies...please specify">
          </div>
        </div>
        <div class="-mx-3 md:flex mb-6">
          <div class="md:w-full px-3">
            <label class="uppercase tracking-wide text-black text-xs font-bold mb-2" for="special_request">
              Special request
            </label>
          <input name="special_request" class="w-full bg-gray-200 text-black border border-gray-200 rounded py-3 px-4 mb-3" id="special_request" type="text" placeholder="please specify..">
          </div>
        </div>
        <div class="-mx-3 md:flex mt-2">
          <div class="md:w-full px-3">
            <button class="md:w-full bg-gray-900 text-white font-bold py-2 px-4 border-b-4 hover:border-b-2 border-gray-500 hover:border-gray-100 rounded-full">
              Submit
            </button>
          </div>
        </div>
      </div>
    </form>
  </div>
</body>
</html>

resources/views/surveys/edit.blade.php
@extends('layouts.apps')

@section('content')

@if ($errors->any())
<div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
        @foreach ($errors->all() as $error)
        <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif


<form action="{{ route('topics.update', $topic->id) }}" method="PATCH">
    @csrf
    @method('PATCH')
    
    <div class="mt-10 sm:mt-0">
        <div class="md:grid md:grid-cols-3 md:gap-6">
            <div class="md:col-span-1">
                <div class="px-4 sm:px-0">
                    <h3 class="text-lg font-medium leading-6 text-gray-900">Information</h3>
                    <p class="mt-1 text-sm text-gray-600">
                        Training topic should be created only by related trainer because it will colerate to trainer's KPI. <br> <br>
                        <strong>Training Status</strong> defines availability of the related topics. <strong>Topic Close</strong> means trainee will not be abel to fill the absence of given topic.
                    </p>
                </div>
            </div>
            <div class="mt-5 md:mt-0 md:col-span-2">
                <form action="#" method="POST">
                    <div class="shadow overflow-hidden sm:rounded-md">
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <div class="grid grid-cols-6 gap-6">
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="topic_name" class="block text-sm font-medium text-gray-700">Topic Title</label>
                                    <input type="text" name="topic_name" value="{{ $topic->topic_name }}" id="topic_name" autocomplete="topic_name" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Training Topic">
                                </div>
                                
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="training_method" class="block text-sm font-medium text-gray-700">Method</label>
                                    <select type="text" name="training_method" value="{{ $topic->training_method }}" id="training_method" autocomplete="training_method" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                        <option value="class">Class</option>
                                        <option value="briefing">Briefing</option>
                                        <option value="role-play">Role-Play</option>
                                        <option value="online-essay">Online-Essay</option>
                                        <option value="online-webinar">Online-Webinar</option>
                                        <option value="one-on-one">One-on-One</option>
                                    </select>
                                </div>
                                <div class="col-span-6">
                                    <label for="topic_detail" class="block text-sm font-medium text-gray-700">Topic Detail</label>
                                    <textarea type="text" name="topic_detail" value="{{ $topic->topic_detail }}" id="topic_detail" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Further detail related to the topic"></textarea>
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="training_date" class="block text-sm font-medium text-gray-700">Training Date</label>
                                    <input type="date" name="training_date" value="{{ $topic->training_date }}" id="training_date" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="training_time" class="block text-sm font-medium text-gray-700">Training Time</label>
                                    <input type="time" name="training_time" value="{{ $topic->training_time }}" id="training_time" autocomplete="training_time" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="training_duration" class="block text-sm font-medium text-gray-700">Duration (minutes)</label>
                                    <input type="number" name="training_duration" value="{{ $topic->training_duration }}" id="training_duration" autocomplete="training_duration" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Minimal 15 minutes">
                                </div>
                                <div class="col-span-6 sm:col-span-3">
                                    <label for="training_location" class="block text-sm font-medium text-gray-700">Location</label>
                                    <input type="text" name="training_location" value="{{ $topic->training_location }}" id="training_location" autocomplete="training_location" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Location or training link if the session is online">
                                </div>
                                <div class="col-span-6 sm:col-span-3 lg:col-span-2">
                                    <label for="status" class="block text-sm font-medium text-gray-700">Status</label>
                                    <select type="text" name="status" value="{{ $topic->status }}" id="status" autocomplete="status" class="mt-1 focus:ring-indigo-500 focus:border-indigo-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" placeholder="Minimal 15 minutes">
                                        <option value="open">Open</option>
                                        <option value="close">Close</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                Save
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
</form>


@endsection

resources/views/surveys/index.blade.php
@extends('layouts.apps')


@section('content')

@if ($message = Session::get('success'))
<div class="alert alert-success">
  <p>{{ $message }}</p>
</div>
@endif

  <div class="mt-1">
    <div class="min-h-screen bg-gray-100 py-2 flex flex-col justify-center mx-auto sm:py-2">
      @foreach ($surveys as $survey)
      <div class="p-2 grid grid-cols-1 sm:grid-cols-4 gap-"4>
        <div class="divide-white divide-y p-4 overflow-hidden rounded-3xl bg-indigo-500 border shadow-sm text-white hover:bg-green-500 hover:rotate-1 transition-transform">
          <div>
            <p class="text-white text-xl tracking-wide">{{ $survey->title }} {{ $survey->name }}</p>
            <p class="text-xs text-white">{{ $survey->arrival_date->format('M d, y') }} - {{ $survey->departure_date->format('M d, y') }}</p>
          </div>
          <div class="divide-y w-full divide-blue-200"></div>
          <div class="mt-3">
            <span class="text-sm text-white">
              the guest will be arriving by {{ $survey->carier_code }} ETA {{ $survey->eta }}. <br>
              They will be using {{ $survey->transfer }} from the airport. <br>
              thay are requesting {{ $survey->preference_bed }} bed for their bedding preference <br>
              for food, they are <strong>{{ $survey->preference_food }}</strong> <br>
              thei special request is {{ $survey->special_request }}
    
            </span>
          </div>
        </div>
      </div>
      {!! $surveys->links() !!}
      @endforeach
    </div>
  </div>

@endsection

resources/views/surveys/show.blade.php
@extends('layouts.apps')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Topic</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('topics.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Name:</strong>
                {{ $topic->name }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Details:</strong>
                {{ $topic->detail }}
            </div>
        </div>
    </div>
@endsection

resources/views/surveys/thanks.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <div class="text-red-500 text-bold">Thank You</div>
</body>
</html>